In [3]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [4]:
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
pd.options.display.max_colwidth = 99

# Reading the 'tags' data

We start by reading the 'tags' data from the tags.csv file. Each row in the file consists of entry for a movie (specified by 'movieId'), the user reviewing the movie ('userId') and the user-generated tag ('tag') along with a timestamp. After reading the file, we delete the timestamp and the userId.

In [19]:
cwd = os.getcwd()
tags = pd.read_csv(os.path.join(cwd,"..","MovieLens_Data", "MovieLens", "ml-25m", "tags.csv"))
tags.drop('timestamp', axis= 1, inplace= True)
tags.drop('userId', axis=1, inplace=True)
tags.head()

   movieId               tag
0      260           classic
1      260            sci-fi
2     1732       dark comedy
3     1732    great dialogue
4     7569  so bad it's good

In [6]:
tag_movie_ids = tags['movieId'].nunique()
print(tag_movie_ids)

45251

We find that there are roughly 45k movies with user generated tags

Next, we read the movies.csv file that contains the mapping between 'movieId' in tags.csv and the title of the movie. We also have a column specifying the genre(s) that the movie belongs to.

In [7]:
movies = pd.read_csv(os.path.join(cwd, "..", "MovieLens_Data", "MovieLens", "ml-25m", "movies.csv"))
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

We shall add the information concerning the genre(s) of the movie to its respective tag document. To that end, we replace the '|' character with a space. In cases where no genre information ('no genres listed') is present, we simply leave the cell empty.

In [9]:
movies['genres'] = movies['genres'].str.replace(pat='|', repl = ' ', regex = False)
movies['genres'] = movies['genres'].str.replace(pat='(no genres listed)', repl = ' ', regex = False) 
#regex = False treats () as a part of the string
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

We similarly replace all tags marked #NA with empty spaces. Then, we concatenate all the user generated tags for each movieId into a single document.

In [20]:
tags.fillna("", inplace=True)   #searches for tags marked #NA and replaces them with empty spaces
tags = pd.DataFrame(tags.groupby('movieId')['tag'].apply(lambda x: "%s" % ' '.join(x)))
tags.reset_index(inplace=True)
tags.head()

,movieId,tag
0,1,Owned imdb top 250 Pixar Pixar time travel children comedy funny witty rated-G animation Pixar ...
1,2,Robin Williams time travel fantasy based on children's book board game disappearance giant inse...
2,3,funny best friend duringcreditsstinger fishing old man sequel fever moldy old sequel NO_FA_GANE...
3,4,based on novel or book chick flick divorce interracial relationship single mother CLV chick fli...
4,5,aging baby confidence contraception daughter gynecologist midlife crisis parent child relations...

To this concatenated document, we add the genre information for each movie from 'movies' dataframe.

In [21]:
tags = pd.merge(movies, tags, on = 'movieId')
tags['document'] = tags[['tag','genres']].apply(lambda x: ' '.join(x), axis= 1)
tags.head()

,movieId,title,genres,tag,document
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,Owned imdb top 250 Pixar Pixar time travel children comedy funny witty rated-G animation Pixar ...,Owned imdb top 250 Pixar Pixar time travel children comedy funny witty rated-G animation Pixar ...
1,2,Jumanji (1995),Adventure Children Fantasy,Robin Williams time travel fantasy based on children's book board game disappearance giant inse...,Robin Williams time travel fantasy based on children's book board game disappearance giant inse...
2,3,Grumpier Old Men (1995),Comedy Romance,funny best friend duringcreditsstinger fishing old man sequel fever moldy old sequel NO_FA_GANE...,funny best friend duringcreditsstinger fishing old man sequel fever moldy old sequel NO_FA_GANE...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,based on novel or book chick flick divorce interracial relationship single mother CLV chick fli...,based on novel or book chick flick divorce interracial relationship single mother CLV chick fli...
4,5,Father of the Bride Part II (1995),Comedy,aging baby confidence contraception daughter gynecologist midlife crisis parent child relations...,aging baby confidence contraception daughter gynecologist midlife crisis parent child relations...

# TF-IDF and PCA

Now that the document for each movie is ready, we use the sklearn library to calculate the tf-idf matrix

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(ngram_range=(0,1), min_df = 0.0001, stop_words = 'english')
tfidf_matrix = tfidf.fit_transform(tags['document'])
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(),index=tags.index.tolist())
print(tfidf_df.shape)

(45251, 11514)

Once we have successfully computed the tf-idf matrix, we seek to reduce the dimension of the "movie-space". Currently, as we can see, each movie is a point in 11514-dimensional space. One good way to reduce dimensions would be to use an autoencoder-decoder neural net. However, for the sake of simplicity, we choose to use principal component analysis with 20 principal components.

In [31]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 100)
principalComponents = pca.fit_transform(tfidf_df)
principalComponents_df = pd.DataFrame(data=principalComponents, index=tags.index.tolist())
principalComponents_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
0,-0.053902,0.001941,-0.090299,0.038624,-0.091975,0.213907,-0.005662,-0.176703,-0.002587,0.001484,-0.142637,-0.129378,-0.079494,-0.017493,-0.014489,0.040153,0.011691,-0.003693,0.014503,-0.024713,-0.009831,-0.031223,-0.005833,0.061307,-0.065518,0.167363,-0.030957,0.099275,-0.008962,-0.004856,-0.007229,-0.001281,-0.002724,-0.009079,0.023830,-0.007117,0.018565,-0.011594,-0.039704,0.026380,-0.014405,0.004799,-0.017357,0.056247,-0.005550,-0.020400,-0.021970,-0.039279,0.048986,-0.017062,-0.030888,0.008318,0.008750,0.002632,-0.020732,-0.008630,0.012169,0.003271,0.000345,-0.008942,-0.005750,0.002714,0.025589,-0.010355,-0.000839,0.000324,0.064098,0.038948,0.012707,0.039054,-0.090701,-0.029568,0.014212,0.047605,0.054343,-0.011833,0.011420,-0.038195,-0.002848,-0.074078,0.016931,-0.027356,-0.015927,0.005926,-0.027365,0.033409,0.074901,-0.049445,0.018791,-0.019187,-0.021048,0.024351,-0.023327,0.017804,0.005138,0.026323,0.026088,0.012011,0.022491,-0.016462
1,-0.050437,-0.039635,-0.048211,0.027431,-0.056871,0.087030,-0.011774,-0.029512,-0.011044,0.009921,0.003061,-0.008971,0.038399,0.022337,0.030094,-0.044842,0.091753,-0.025840,-0.016673,-0.016511,0.037359,0.023448,0.004385,-0.035554,0.072769,-0.066631,-0.025597,0.041440,0.064447,-0.048008,0.009643,-0.007415,-0.013958,-0.010509,-0.003672,-0.004365,-0.001043,-0.011314,-0.040035,-0.040429,-0.003547,-0.031200,-0.031486,0.027587,0.028501,-0.037709,-0.060696,-0.178235,0.129527,-0.144315,-0.064606,0.050366,0.008543,0.058318,-0.012003,-0.000710,0.046044,-0.009765,-0.009161,-0.010997,-0.000437,0.004898,0.007941,0.001997,0.002477,-0.046248,0.005331,0.016044,-0.030778,0.029102,-0.026602,-0.012301,-0.002558,-0.013272,-0.010525,-0.009104,-0.012111,-0.004857,-0.022295,0.015286,-0.011892,-0.027192,-0.049991,-0.004189,-0.008930,-0.031242,0.023147,-0.022727,0.000757,-0.003416,-0.043174,0.000338,0.006149,0.037176,-0.024148,-0.005073,-0.010364,0.030464,-0.004218,0.078701
2,-0.041464,0.014659,-0.032051,-0.002705,-0.028249,0.010320,-0.025370,0.015745,-0.023086,-0.022280,0.033749,-0.022710,0.009204,-0.025819,-0.007561,-0.044778,-0.011158,-0.016536,-0.007122,0.002041,-0.006886,-0.002818,-0.015256,-0.007977,-0.000767,0.003285,-0.033550,-0.000419,-0.006622,-0.009244,-0.005153,-0.004653,0.006325,-0.014924,-0.026375,0.003130,-0.000529,-0.015185,-0.020428,0.001939,-0.002603,-0.020661,-0.011908,-0.011223,0.009968,-0.011659,-0.002934,-0.003491,0.015535,0.031989,-0.026164,-0.004254,-0.004876,0.010071,-0.000016,0.009755,-0.026896,-0.008211,0.002028,-0.004919,-0.018900,-0.012994,0.010864,-0.036516,0.002691,-0.031774,0.032698,0.030251,-0.043365,0.023278,-0.117252,-0.002530,-0.057592,-0.054358,-0.015718,0.030380,-0.021353,0.056494,0.018134,-0.055271,-0.001967,0.034729,0.075715,-0.051609,-0.045976,-0.012301,-0.015226,0.018644,0.013059,-0.016501,-0.011628,0.017752,-0.005350,0.068206,0.000980,0.009078,0.016970,0.015576,-0.051262,-0.060396
3,-0.032691,0.040974,0.027383,-0.034920,-0.058024,0.011567,-0.051395,0.014621,-0.042757,0.004052,0.020910,-0.024359,0.129875,0.104643,0.002600,-0.005805,-0.049043,0.003106,0.015289,-0.001348,-0.019067,-0.009113,0.011071,0.003356,-0.011101,-0.012209,-0.008684,0.001018,-0.013870,0.005636,-0.018443,-0.005962,-0.078829,-0.010702,0.038423,0.012352,0.006462,-0.003357,0.024544,0.000269,0.032501,-0.034684,-0.008611,-0.024009,-0.031740,0.028389,0.012791,-0.008123,0.055680,0.014456,0.057642,-0.054226,0.003482,0.007307,0.022695,-0.041644,-0.003782,-0.038207,0.013115,0.006805,-0.003679,0.006594,0.016835,-0.003776,-0.020227,0.000676,0.018813,0.010066,-0.010447,0.005863,-0.004999,0.008975,0.000711,0.011536,-0.000197,-0.002732,-0.024778,0.012069,-0.031622,-0.014761,0.037687,-0.011603,0.021866,0.018040,0.060991,0.014780,0.010137,-0.025646,-0.025820,0.011096,-0.013171,0.005473,-0.023975,0.018354,-0.019530,0.004318,0.002310,-0.003647,0.015942,-0.000985
4,-0.040990,0.060512,-0.049049,0.012286,-0.026016,0.018287,-0.014618,-0.015119,-0.056137,0.003816,0.024843,-0.014091,0.006584,-0.025411,0.014291,-0.061792,0.024507,-0.032075,0.012876,-0.000151,-0.043499,0.005007,0.029910,-0.002406,0.023426,-0.042744,-0.023115,0.013742,-0.003818,-0.042212,-0.028089,-0.048031,-0.111075,-0.052328,0.148414,-0.026056,0.052600,-0.032564,-0.040366,-0.025258,0.033314,-0.036258,-0.031571,0.073428,-0.032782,-0.018838,-0.066596,0.013684,-0.017430,0.006949,0.003597,0.012179,0.000960,0.014175,-0.004747,0.003595,0.010985,-0.027273,0.000389,-0.007776,-0.021605,-0.021307,-0.003155,-0.029430,-0.003697,-0.020221,0.022072,0.016400,-0.045549,0.039506,-0.098618,-0.001642,-0.046797,-0.052727,0.000278,0.018388,-0.009005,0.062038,0.042651,-0.019056,0.018774,0.048243,0.055088,-0.024844,-0.020419,0.006352,-0.024149,0.009121,-0.000438,-0.014749,-0.016557,0.014180,-0.041603,0.056145,0.022874,0.031342,0.062705,0.029793,-0.037505,-0.034923

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
# similarity_matrix_df = pd.DataFrame(cosine_similarity(principalComponents), index=tags.index.tolist())
similarity_matrix_df = pd.DataFrame(euclidean_distances(principalComponents), index=tags.index.tolist())
# similarity_matrix_df = pd.DataFrame(cosine_similarity(tfidf_matrix), index=tags.index.tolist())
# similarity_matrix_df = pd.DataFrame(euclidean_distances(tfidf_matrix), index=tags.index.tolist())
similarity_matrix_df.head()

In [38]:
#input a numpy array of movieids and provide recommendations of those movies that have the highest average similarity score

def get_content_recommendations(movie_ids, movies, similarity_matrix_df, num = 5):
    movie_titles = pd.DataFrame(index=[movie_ids], columns=['title'])
    index_from_movie_ids = np.zeros(len(movie_ids))
    
    for i in range(len(movie_ids)):
        movie_titles['title'].iloc[i] = movies[movies['movieId'] == movie_ids[i]]['title'].iloc[0]
        index_from_movie_ids[i] = movies[movies['movieId'] == movie_ids[i]].index.values[0]
        
    similarity_overall_score = np.zeros((similarity_matrix_df.shape[0],1))
    
    for i in range(len(movie_ids)):
        similarity_overall_score=np.add(similarity_matrix_df[[index_from_movie_ids[i]]].values, similarity_overall_score)    
    
    similar_movies_df = pd.DataFrame(similarity_overall_score, index=similarity_matrix_df.index.tolist())
    similar_movies_df.drop(labels=index_from_movie_ids, axis=0, inplace=True)
    similar_movies_df.columns = ['overall_cosine_similarity']
    similar_movies_df.sort_values(by = ['overall_cosine_similarity'], ascending=False, inplace=True)
    similar_movies_df = similar_movies_df.head(num)
    similar_movies_df = similar_movies_df.join(movies, how='left')
    
    return similar_movies_df
    
#     for i in range(num):
#         similar_movies_df['title'].iloc[i] = movies[movies['index'] == similar_movies_df['index'].iloc[i]]['title'].iloc[0]
#     similar_movies_df.reset_index(inplace=True)
#     similar_movies_df.insert(1, column='title', value=np.nan)
#     similar_movies_df.insert(2, column='movieId', value=np.nan)
    
#     movie_rec_titles = pd.DataFrame(index=range(num), columns=['movieId','title'])
#     movie_rec_titles['movieId'] = similar_movies_df['movieId']
    
#     for i in range(num):
#         movie_rec_titles['title'].iloc[i] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[i]]['title'].iloc[0]

In [ ]:
def lookup_movie_id_by_title(movie_title):
    return movies[movies.title.str.contains(movie_title)]

In [44]:
lookup_movie_id_by_title("Star Wars")

,movieId,title,genres
257,260,Star Wars: Episode IV - A New Hope (1977),Action Adventure Sci-Fi
1166,1196,Star Wars: Episode V - The Empire Strikes Back (1980),Action Adventure Sci-Fi
1179,1210,Star Wars: Episode VI - Return of the Jedi (1983),Action Adventure Sci-Fi
2537,2628,Star Wars: Episode I - The Phantom Menace (1999),Action Adventure Sci-Fi
5270,5378,Star Wars: Episode II - Attack of the Clones (2002),Action Adventure Sci-Fi IMAX
9952,33493,Star Wars: Episode III - Revenge of the Sith (2005),Action Adventure Sci-Fi
12593,61160,Star Wars: The Clone Wars (2008),Action Adventure Animation Sci-Fi
14912,79006,Empire of Dreams: The Story of the 'Star Wars' Trilogy (2004),Documentary
21250,109713,Star Wars: Threads of Destiny (2014),Action Adventure Sci-Fi
25055,122886,Star Wars: Episode VII - The Force Awakens (2015),Action Adventure Fantasy Sci-Fi IMAX
29997,135216,The Star Wars Holiday Special (1978),Adventure Children Comedy Sci-Fi
30524,136485,Robot Chicken: Star Wars (2007),Animation Comedy Sci-Fi
36606,150688,Plastic Galaxy: The Story of Star Wars Toys (2014),Documentary
43646,166528,Rogue One: A Star Wars Story (2016),Action Adventure Fantasy Sci-Fi
49883,179819,Star Wars: The Last Jedi (2017),Action Adventure Fantasy Sci-Fi
50585,181355,Robot Chicken: Star Wars Episode II (2008),Comedy Sci-Fi
50586,181357,Robot Chicken: Star Wars Episode III (2010),Comedy Sci-Fi
51308,182857,Star Wars: The Legacy Revealed (2007),Documentary
52111,184593,Star Wars Downunder (2013),Sci-Fi
53524,187595,Solo: A Star Wars Story (2018),Action Adventure Children Sci-Fi
56918,195217,Star Wars: Dresca,Sci-Fi

In [53]:
movie_ids = [2571]
movie_titles = pd.DataFrame(index=[movie_ids], columns=['title'])
index_from_movie_ids = np.zeros(len(movie_ids))

for i in range(len(movie_ids)):
        movie_titles['title'].iloc[i] = movies[movies['movieId'] == movie_ids[i]]['title'].iloc[0]
        index_from_movie_ids[i] = movies[movies['movieId'] == movie_ids[i]].index.values[0]

# movie_titles.head()
print(index_from_movie_ids)
# movies[movies['movieId'] == 51540].index.values[0]

[2480.]

In [54]:
np.round(cosine_similarity(tfidf_matrix[2480,:], tfidf_matrix[6247,:]),10)

array([[0.]])

In [40]:
movie_ids = [1196]
alpha = get_content_recommendations(movie_ids, movies, similarity_matrix_cosine_df, num=5)
print(alpha)
# print(alpha['movieId'].values)
# movies.query('movieId == 24501')

       overall_cosine_similarity  movieId  \
27034                   0.814767   128155
26243                   0.802151   125485
37684                   0.764345   153178
39925                   0.740150   158288
39647                   0.730017   157681

                                         title                genres
27034  The Last Days of Lehman Brothers (2009)     Documentary Drama
26243                 We Were Strangers (1949)  Action Drama Romance
37684                           Insiang (1976)                 Drama
39925                             Saamy (2003)          Action Drama
39647                  Gotta Kick It Up (2002)          Comedy Drama

In [49]:
tags.query('movieId== 89763').tag.values

0        0.000000
1        0.000000
2        0.000000
3        0.000000
4        0.000000
5        0.000000
6        0.000000
7        0.000000
8        0.000000
9        0.000000
10       0.000000
11       0.000000
12       0.000000
13       0.000000
14       0.000000
15       0.000000
16       0.000000
17       0.000000
18       0.000000
19       0.000000
20       0.000000
21       0.000000
22       0.000000
23       0.000000
24       0.000000
25       0.000000
26       0.000000
27       0.000000
28       0.000000
29       0.000000
30       0.000000
31       0.000000
32       0.000000
33       0.000000
34       0.000000
35       0.000000
36       0.000000
37       0.000000
38       0.212194
39       0.000000
40       0.000000
41       0.000000
42       0.000000
43       0.000000
44       0.000000
45       0.000000
46       0.000000
47       0.000000
48       0.000000
49       0.000000
50       0.000000
51       0.000000
52       0.000000
53       0.000000
54       0.000000
55       0.000000
56       0.000000
57       0.000000
58       0.000000
59       0.000000
60       0.000000
61       0.000000
62       0.000000
63       0.000000
64       0.000000
65       0.000000
66       0.000000
67       0.000000
68       0.000000
69       0.000000
70       0.000000
71       0.000000
72       0.000000
73       0.000000
74       0.000000
75       0.000000
76       0.000000
77       0.000000
78       0.000000
79       0.000000
80       0.000000
81       0.000000
82       0.000000
83       0.000000
84       0.000000
85       0.000000
86       0.000000
87       0.000000
88       0.000000
89       0.000000
90       0.000000
91       0.000000
92       0.000000
93       0.000000
94       0.000000
95       0.000000
96       0.000000
97       0.000000
98       0.000000
99       0.000000
100      0.000000
101      0.000000
102      0.000000
103      0.000000
104      0.000000
105      0.000000
106      0.000000
107      0.000000
108      0.000000
109      0.000000
110      0.000000
111      0.000000
112      0.000000
113      0.000000
114      0.000000
115      0.000000
116      0.000000
117      0.000000
118      0.000000
119      0.000000
120      0.000000
121      0.000000
122      0.000000
123      0.000000
124      0.000000
125      0.000000
126      0.000000
127      0.000000
128      0.000000
129      0.000000
130      0.000000
131      0.000000
132      0.000000
133      0.000000
134      0.000000
135      0.000000
136      0.000000
137      0.000000
138      0.000000
139      0.000000
140      0.000000
141      0.000000
142      0.000000
143      0.000000
144      0.000000
145      0.000000
146      0.000000
147      0.000000
148      0.000000
149      0.000000
150      0.000000
151      0.000000
152      0.000000
153      0.000000
154      0.000000
155      0.000000
156      0.000000
157      0.000000
158      0.000000
159      0.000000
160      0.000000
161      0.000000
162      0.000000
163      0.000000
164      0.000000
165      0.000000
166      0.000000
167      0.000000
168      0.000000
169      0.000000
170      0.000000
171      0.000000
172      0.000000
173      0.000000
174      0.000000
175      0.000000
176      0.000000
177      0.000000
178      0.000000
179      0.000000
180      0.000000
181      0.000000
182      0.000000
183      0.000000
184      0.000000
185      0.000000
186      0.000000
187      0.000000
188      0.000000
189      0.000000
190      0.000000
191      0.000000
192      0.000000
193      0.000000
194      0.000000
195      0.000000
196      0.000000
197      0.000000
198      0.000000
199      0.000000
200      0.000000
201      0.000000
202      0.000000
203      0.000000
204      0.000000
205      0.000000
206      0.000000
207      0.000000
208      0.000000
209      0.000000
210      0.000000
211      0.000000
212      0.000000
213      0.000000
214      0.000000
215      0.000000
216      0.000000
217      0.000000
218      0.000000
219      0.000000
220      0.000000
221      0.000000
222      0.000000
223      0.000000
224      0.000000
225      0.000000
226      0.000000
227      0.000000
228      0.000000
229      0.000000
230      0.000000
231      0.000000
232      0.000000
233      0.000000
234      0.000000
235      0.000000
236      0.000000
237      0.000000
238      0.000000
239      0.000000
240      0.000000
241      0.000000
242      0.000000
243      0.000000
244      0.000000
245      0.000000
246      0.000000
247      0.000000
248      0.000000
249      0.000000
250      0.000000
251      0.000000
252      0.000000
253      0.000000
254      0.000000
255      0.000000
256      0.000000
257      0.000000
258      0.000000
259      0.000000
260      0.000000
261      0.000000
262      0.000000
263      0.000000
264      0.000000
265      0.000000
266      0.000000
267      0.000000
268      0.000000
269      0.000000
270      0.000000
271      0.000000
272      0.000000
273      0.000000
274      0.000000
275      0.000000
276      0.000000
277      0.000000
278      0.000000
279      0.000000
280      0.000000
281      0.000000
282      0.000000
283      0.000000
284      0.000000
285      0.000000
286      0.000000
287      0.000000
288      0.000000
289      0.000000
290      0.000000
291      0.000000
292      0.000000
293      0.000000
294      0.000000
295      0.000000
296      0.000000
297      0.000000
298      0.000000
299      0.000000
300      0.000000
301      0.000000
302      0.000000
303      0.000000
304      0.000000
305      0.000000
306      0.000000
307      0.000000
308      0.000000
309      0.000000
310      0.000000
311      0.000000
312      0.000000
313      0.000000
314      0.000000
315      0.000000
316      0.000000
317      0.000000
318      0.000000
319      0.000000
320      0.000000
321      0.000000
322      0.000000
323      0.000000
324      0.000000
325      0.000000
326      0.000000
327      0.000000
328      0.000000
329      0.000000
330      0.000000
331      0.000000
332      0.000000
333      0.000000
334      0.000000
335      0.000000
336      0.000000
337      0.000000
338      0.000000
339      0.000000
340      0.000000
341      0.000000
342      0.000000
343      0.000000
344      0.000000
345      0.000000
346      0.000000
347      0.000000
348      0.000000
349      0.000000
350      0.000000
351      0.000000
352      0.000000
353      0.000000
354      0.000000
355      0.000000
356      0.000000
357      0.000000
358      0.000000
359      0.000000
360      0.000000
361      0.000000
362      0.000000
363      0.000000
364      0.000000
365      0.000000
366      0.000000
367      0.000000
368      0.000000
369      0.000000
370      0.000000
371      0.000000
372      0.000000
373      0.000000
374      0.000000
375      0.000000
376      0.000000
377      0.000000
378      0.000000
379      0.000000
380      0.000000
381      0.000000
382      0.000000
383      0.000000
384      0.000000
385      0.000000
386      0.000000
387      0.000000
388      0.000000
389      0.000000
390      0.000000
391      0.000000
392      0.000000
393      0.000000
394      0.000000
395      0.000000
396      0.000000
397      0.000000
398      0.000000
399      0.000000
400      0.000000
401      0.000000
402      0.000000
403      0.000000
404      0.000000
405      0.000000
406      0.000000
407      0.000000
408      0.000000
409      0.000000
410      0.000000
411      0.000000
412      0.000000
413      0.000000
414      0.000000
415      0.000000
416      0.000000
417      0.000000
418      0.000000
419      0.000000
420      0.000000
421      0.000000
422      0.000000
423      0.000000
424      0.000000
425      0.000000
426      0.000000
427      0.000000
428      0.000000
429      0.000000
430      0.000000
431      0.000000
432      0.000000
433      0.000000
434      0.000000
435      0.000000
436      0.000000
437      0.000000
438      0.000000
439      0.000000
440      0.000000
441      0.000000
442      0.000000
443      0.000000
444      0.000000
445      0.000000
446      0.000000
447      0.000000
448      0.000000
449      0.000000
450      0.000000
451      0.000000
452      0.000000
453      0.000000
454      0.000000
455      0.000000
456      0.000000
457      0.000000
458      0.000000
459      0.000000
460      0.000000
461      0.000000
462      0.000000
463      0.000000
464      0.000000
465      0.000000
466      0.000000
467      0.000000
468      0.000000
469      0.000000
470      0.000000
471      0.000000
472      0.000000
473      0.000000
474      0.000000
475      0.000000
476      0.000000
477      0.000000
478      0.000000
479      0.000000
480      0.000000
481      0.000000
482      0.000000
483      0.000000
484      0.000000
485      0.000000
486      0.000000
487      0.000000
488      0.000000
489      0.000000
490      0.000000
491      0.000000
492      0.000000
493      0.000000
494      0.000000
495      0.000000
496      0.000000
497      0.000000
498      0.000000
           ...
11015    0.000000
11016    0.000000
11017    0.000000
11018    0.000000
11019    0.000000
11020    0.000000
11021    0.000000
11022    0.000000
11023    0.000000
11024    0.000000
11025    0.000000
11026    0.000000
11027    0.000000
11028    0.000000
11029    0.000000
11030    0.000000
11031    0.000000
11032    0.000000
11033    0.000000
11034    0.000000
11035    0.000000
11036    0.000000
11037    0.000000
11038    0.000000
11039    0.000000
11040    0.000000
11041    0.000000
11042    0.000000
11043    0.000000
11044    0.000000
11045    0.000000
11046    0.000000
11047    0.000000
11048    0.000000
11049    0.000000
11050    0.000000
11051    0.000000
11052    0.000000
11053    0.000000
11054    0.000000
11055    0.000000
11056    0.000000
11057    0.000000
11058    0.000000
11059    0.000000
11060    0.000000
11061    0.000000
11062    0.000000
11063    0.000000
11064    0.000000
11065    0.000000
11066    0.000000
11067    0.000000
11068    0.000000
11069    0.000000
11070    0.000000
11071    0.000000
11072    0.000000
11073    0.000000
11074    0.000000
11075    0.000000
11076    0.000000
11077    0.000000
11078    0.000000
11079    0.000000
11080    0.000000
11081    0.000000
11082    0.000000
11083    0.000000
11084    0.000000
11085    0.000000
11086    0.000000
11087    0.000000
11088    0.000000
11089    0.000000
11090    0.000000
11091    0.000000
11092    0.000000
11093    0.000000
11094    0.000000
11095    0.000000
11096    0.000000
11097    0.000000
11098    0.000000
11099    0.000000
11100    0.000000
11101    0.000000
11102    0.000000
11103    0.000000
11104    0.000000
11105    0.000000
11106    0.000000
11107    0.000000
11108    0.000000
11109    0.000000
11110    0.000000
11111    0.000000
11112    0.000000
11113    0.000000
11114    0.000000
11115    0.000000
11116    0.000000
11117    0.000000
11118    0.000000
11119    0.000000
11120    0.000000
11121    0.000000
11122    0.000000
11123    0.000000
11124    0.000000
11125    0.000000
11126    0.000000
11127    0.000000
11128    0.000000
11129    0.000000
11130    0.000000
11131    0.000000
11132    0.000000
11133    0.000000
11134    0.000000
11135    0.000000
11136    0.000000
11137    0.000000
11138    0.000000
11139    0.000000
11140    0.000000
11141    0.000000
11142    0.000000
11143    0.000000
11144    0.000000
11145    0.000000
11146    0.000000
11147    0.000000
11148    0.000000
11149    0.000000
11150    0.000000
11151    0.000000
11152    0.000000
11153    0.000000
11154    0.000000
11155    0.000000
11156    0.000000
11157    0.000000
11158    0.000000
11159    0.000000
11160    0.000000
11161    0.000000
11162    0.000000
11163    0.000000
11164    0.000000
11165    0.000000
11166    0.000000
11167    0.000000
11168    0.000000
11169    0.000000
11170    0.000000
11171    0.000000
11172    0.000000
11173    0.000000
11174    0.000000
11175    0.000000
11176    0.000000
11177    0.000000
11178    0.000000
11179    0.000000
11180    0.000000
11181    0.000000
11182    0.000000
11183    0.000000
11184    0.000000
11185    0.000000
11186    0.000000
11187    0.000000
11188    0.000000
11189    0.000000
11190    0.000000
11191    0.000000
11192    0.000000
11193    0.000000
11194    0.000000
11195    0.000000
11196    0.000000
11197    0.000000
11198    0.000000
11199    0.000000
11200    0.000000
11201    0.000000
11202    0.000000
11203    0.000000
11204    0.000000
11205    0.000000
11206    0.000000
11207    0.000000
11208    0.000000
11209    0.000000
11210    0.000000
11211    0.000000
11212    0.000000
11213    0.000000
11214    0.000000
11215    0.000000
11216    0.000000
11217    0.000000
11218    0.000000
11219    0.000000
11220    0.000000
11221    0.000000
11222    0.000000
11223    0.000000
11224    0.000000
11225    0.000000
11226    0.000000
11227    0.000000
11228    0.000000
11229    0.000000
11230    0.000000
11231    0.000000
11232    0.000000
11233    0.000000
11234    0.000000
11235    0.000000
11236    0.000000
11237    0.000000
11238    0.000000
11239    0.000000
11240    0.000000
11241    0.000000
11242    0.000000
11243    0.000000
11244    0.000000
11245    0.000000
11246    0.000000
11247    0.000000
11248    0.000000
11249    0.000000
11250    0.000000
11251    0.000000
11252    0.000000
11253    0.000000
11254    0.000000
11255    0.000000
11256    0.000000
11257    0.000000
11258    0.000000
11259    0.000000
11260    0.000000
11261    0.000000
11262    0.000000
11263    0.000000
11264    0.000000
11265    0.000000
11266    0.000000
11267    0.000000
11268    0.000000
11269    0.000000
11270    0.000000
11271    0.000000
11272    0.000000
11273    0.000000
11274    0.000000
11275    0.000000
11276    0.000000
11277    0.000000
11278    0.000000
11279    0.000000
11280    0.000000
11281    0.000000
11282    0.000000
11283    0.000000
11284    0.000000
11285    0.000000
11286    0.000000
11287    0.000000
11288    0.000000
11289    0.000000
11290    0.000000
11291    0.000000
11292    0.000000
11293    0.000000
11294    0.000000
11295    0.000000
11296    0.000000
11297    0.000000
11298    0.000000
11299    0.000000
11300    0.000000
11301    0.000000
11302    0.000000
11303    0.000000
11304    0.000000
11305    0.000000
11306    0.000000
11307    0.000000
11308    0.000000
11309    0.000000
11310    0.000000
11311    0.000000
11312    0.000000
11313    0.000000
11314    0.000000
11315    0.000000
11316    0.000000
11317    0.000000
11318    0.000000
11319    0.000000
11320    0.000000
11321    0.000000
11322    0.000000
11323    0.000000
11324    0.000000
11325    0.000000
11326    0.000000
11327    0.000000
11328    0.000000
11329    0.000000
11330    0.000000
11331    0.000000
11332    0.000000
11333    0.000000
11334    0.000000
11335    0.000000
11336    0.000000
11337    0.000000
11338    0.000000
11339    0.000000
11340    0.000000
11341    0.000000
11342    0.000000
11343    0.000000
11344    0.000000
11345    0.000000
11346    0.000000
11347    0.000000
11348    0.000000
11349    0.000000
11350    0.000000
11351    0.000000
11352    0.000000
11353    0.000000
11354    0.000000
11355    0.000000
11356    0.000000
11357    0.000000
11358    0.000000
11359    0.000000
11360    0.000000
11361    0.000000
11362    0.000000
11363    0.000000
11364    0.000000
11365    0.000000
11366    0.000000
11367    0.000000
11368    0.000000
11369    0.000000
11370    0.000000
11371    0.000000
11372    0.000000
11373    0.000000
11374    0.000000
11375    0.000000
11376    0.000000
11377    0.000000
11378    0.000000
11379    0.000000
11380    0.000000
11381    0.000000
11382    0.000000
11383    0.000000
11384    0.000000
11385    0.000000
11386    0.000000
11387    0.000000
11388    0.000000
11389    0.000000
11390    0.000000
11391    0.000000
11392    0.000000
11393    0.000000
11394    0.000000
11395    0.000000
11396    0.000000
11397    0.000000
11398    0.000000
11399    0.000000
11400    0.000000
11401    0.000000
11402    0.000000
11403    0.000000
11404    0.000000
11405    0.000000
11406    0.000000
11407    0.000000
11408    0.000000
11409    0.000000
11410    0.000000
11411    0.000000
11412    0.000000
11413    0.000000
11414    0.000000
11415    0.000000
11416    0.000000
11417    0.000000
11418    0.000000
11419    0.000000
11420    0.000000
11421    0.000000
11422    0.000000
11423    0.000000
11424    0.000000
11425    0.000000
11426    0.000000
11427    0.000000
11428    0.000000
11429    0.000000
11430    0.000000
11431    0.000000
11432    0.000000
11433    0.000000
11434    0.000000
11435    0.000000
11436    0.000000
11437    0.000000
11438    0.000000
11439    0.000000
11440    0.000000
11441    0.000000
11442    0.000000
11443    0.000000
11444    0.000000
11445    0.000000
11446    0.000000
11447    0.000000
11448    0.000000
11449    0.000000
11450    0.000000
11451    0.000000
11452    0.000000
11453    0.000000
11454    0.000000
11455    0.000000
11456    0.000000
11457    0.000000
11458    0.000000
11459    0.000000
11460    0.000000
11461    0.000000
11462    0.000000
11463    0.000000
11464    0.000000
11465    0.000000
11466    0.000000
11467    0.000000
11468    0.000000
11469    0.000000
11470    0.000000
11471    0.000000
11472    0.000000
11473    0.000000
11474    0.000000
11475    0.000000
11476    0.000000
11477    0.000000
11478    0.000000
11479    0.000000
11480    0.000000
11481    0.000000
11482    0.000000
11483    0.000000
11484    0.000000
11485    0.000000
11486    0.000000
11487    0.000000
11488    0.000000
11489    0.000000
11490    0.000000
11491    0.000000
11492    0.000000
11493    0.000000
11494    0.000000
11495    0.000000
11496    0.000000
11497    0.000000
11498    0.000000
11499    0.000000
11500    0.000000
11501    0.000000
11502    0.000000
11503    0.000000
11504    0.000000
11505    0.000000
11506    0.000000
11507    0.000000
11508    0.000000
11509    0.000000
11510    0.000000
11511    0.000000
11512    0.000000
11513    0.000000
Name: 17072, Length: 11514, dtype: float64

In [50]:
movie_ids = [260, 234, 456, 789]
similar_overall_score = np.zeros((similarity_matrix_df.shape[0],1))
similar_overall_score = np.add(similarity_matrix_df[[movie_ids[0]]].values, similar_overall_score)
similar_overall_score = np.add(similarity_matrix_df[[movie_ids[1]]].values, similar_overall_score)
similar_overall_score = np.add(similarity_matrix_df[[movie_ids[2]]].values, similar_overall_score)
similar_overall_score = np.add(similarity_matrix_df[[movie_ids[3]]].values, similar_overall_score)
similar_movies_new_df = pd.DataFrame(similar_overall_score)
similar_movies_new_df.columns = ['cosine_similarity']
# similar_movies_new_df.insert(1, column='title', value=np.nan)
# similar_movies_new_df.insert(2, column='movieId', value=np.nan)
similar_movies_new_df.sort_values(by = ['cosine_similarity'], ascending=False, inplace=True)
# print(similar_overall_score.shape)
similar_movies_new_df = similar_movies_new_df.head()
print(similar_movies_new_df)
similar_movies_new_df = similar_movies_new_df.join(movies, how = 'left')
similar_movies_new_df
# for i in range(3):
#         similar_movies_new_df['title'].iloc[i] = movies[movies.index == similar_movies_df.index.iloc[i]]['title'].iloc[0]
# similar_movies_new_df.reset_index
# similar_movies_new_df.index.tolist(1,1)
# print(len(movie_ids))
# type(similar_movies_new_df)
# print(similar_overall_score)

       cosine_similarity
456             1.069405
260             1.051592
234             1.029656
789             1.022092
32614           0.806088

       cosine_similarity  movieId                     title            genres
456             1.069405      461            Go Fish (1994)     Drama Romance
260             1.051592      263  Ladybird Ladybird (1994)             Drama
234             1.029656      237       Forget Paris (1995)    Comedy Romance
789             1.022092      805    Time to Kill, A (1996)    Drama Thriller
32614           0.806088   141347             Watusi (1959)  Action Adventure

In [119]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
similar_movies_df.sort_values(by = ['cosine_similarity'], ascending=False, inplace=True)

In [127]:
# movie_ids = [260, 234, 456, 789]
# movie_titles = pd.DataFrame(index=[movie_ids], columns=['title'])
# print(movie_titles)
# for i in range(len(movie_ids)):
#         movie_titles['title'].iloc[i] = movies[movies['movieId'] == movie_ids[i]]['title'].iloc[0]
# print(movie_titles)

    title
260   NaN
234   NaN
456   NaN
789   NaN
                                                 title
260          Star Wars: Episode IV - A New Hope (1977)
234                                Exit to Eden (1994)
456                                       Fresh (1994)
789  I, the Worst of All (Yo, la peor de todas) (1990)

In [22]:
movies.query('movieId == 234')

     movieId                title  genres
231      234  Exit to Eden (1994)  Comedy

In [61]:
movie_rec_titles = pd.DataFrame(index=range(5), columns=['movieId','title'])
print(movie_rec_titles)
movie_rec_titles['movieId'] = alpha['movieId'] 
# for i in range(5):
#         movie_rec_titles.title.iloc[i] = movies[movies['movieId'] == movie_rec_titles.movieId.iloc[i]]['title'].iloc[0]
print(movie_rec_titles)
movie_rec_titles['title'].iloc[0] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[0]]['title'].iloc[0]
movie_rec_titles['title'].iloc[1] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[1]]['title'].iloc[0]
# movie_rec_titles['title'].iloc[2] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[2]]['title'].iloc[0]
# movie_rec_titles['title'].iloc[3] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[3]]['title'].iloc[0]
# movie_rec_titles['title'].iloc[4] = movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[4]]['title'].iloc[0]

print(movie_rec_titles)

  movieId title
0     NaN   NaN
1     NaN   NaN
2     NaN   NaN
3     NaN   NaN
4     NaN   NaN
   movieId title
0     8999   NaN
1     8784   NaN
2    14552   NaN
3     9323   NaN
4    24501   NaN
   movieId                                 title
0     8999  That's Entertainment, Part II (1976)
1     8784                   Garden State (2004)
2    14552                                   NaN
3     9323                                   NaN
4    24501                                   NaN

In [93]:
# print(movies[movies['movieId'] == movie_rec_titles['movieId'].iloc[2]]['title'].iloc[0])
# print(movies[movies['movieId'] == 14552]['title'].iloc[0])
# print(movie_rec_titles['movieId'].iloc[2])
# movies.query('movieId == 14552')['title'].iloc[0]
movies.query('movieId == 8784')

      movieId                title                genres
8070     8784  Garden State (2004)  Comedy|Drama|Romance

In [280]:
movie_ids = [260, 234, 456, 789]
movie_titles = pd.DataFrame(index=[movie_ids], columns=['title'])

movie_rec_titles = pd.DataFrame(index=range(5), columns=['movieId','title'])

# movie_titles.reset_index(inplace=True)
# movie_titles.rename(columns = {'movieId'}, inplace = True)
# movie_titles.index = movie_titles['movieId']
#     movie_titles = pd.Series(index=[movie_ids])

for i in range(len(movie_ids)):
    movie_titles.iloc[i] = movies[movies['movieId'] == movie_ids[i]]['title'].iloc[0]

# for i in range(5):
#     movie_rec_titles['movidId'].iloc[i] = get
    
# print(movie_titles)
# print(pd.Series(movie_titles['title'].values))    
alpha = get_content_recommendations(movie_ids, similarity_matrix_df)
print(alpha)
print(movie_titles)
# print(movie_rec_titles)

   movieId  overall_cosine_similarity
0    14810                   1.681837
1    14552                   1.666567
2     8999                   1.666377
3    11335                   1.658928
4    15330                   1.650560
                                                 title
260          Star Wars: Episode IV - A New Hope (1977)
234                                Exit to Eden (1994)
456                                       Fresh (1994)
789  I, the Worst of All (Yo, la peor de todas) (1990)

In [160]:
movie_ids = [260, 234, 456, 789]
similarity_overall_score=np.zeros((similarity_matrix_df.shape[0], 1))
similarity_overall_score_df = pd.DataFrame(similarity_overall_score)

# similarity_overall_score=np.add(similarity_matrix_df[[movie_ids[i]]].values for i in range(len(movie_ids)))
print(similarity_overall_score_df)
# print(similarity_overall_score)

         0
0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
5      0.0
6      0.0
7      0.0
8      0.0
9      0.0
10     0.0
11     0.0
12     0.0
13     0.0
14     0.0
15     0.0
16     0.0
17     0.0
18     0.0
19     0.0
20     0.0
21     0.0
22     0.0
23     0.0
24     0.0
25     0.0
26     0.0
27     0.0
28     0.0
29     0.0
30     0.0
31     0.0
32     0.0
33     0.0
34     0.0
35     0.0
36     0.0
37     0.0
38     0.0
39     0.0
40     0.0
41     0.0
42     0.0
43     0.0
44     0.0
45     0.0
46     0.0
47     0.0
48     0.0
49     0.0
50     0.0
51     0.0
52     0.0
53     0.0
54     0.0
55     0.0
56     0.0
57     0.0
58     0.0
59     0.0
60     0.0
61     0.0
62     0.0
63     0.0
64     0.0
65     0.0
66     0.0
67     0.0
68     0.0
69     0.0
70     0.0
71     0.0
72     0.0
73     0.0
74     0.0
75     0.0
76     0.0
77     0.0
78     0.0
79     0.0
80     0.0
81     0.0
82     0.0
83     0.0
84     0.0
85     0.0
86     0.0
87     0.0
88     0.0
89     0.0
90     0.0
91     0.0
92     0.0
93     0.0
94     0.0
95     0.0
96     0.0
97     0.0
98     0.0
99     0.0
100    0.0
101    0.0
102    0.0
103    0.0
104    0.0
105    0.0
106    0.0
107    0.0
108    0.0
109    0.0
110    0.0
111    0.0
112    0.0
113    0.0
114    0.0
115    0.0
116    0.0
117    0.0
118    0.0
119    0.0
120    0.0
121    0.0
122    0.0
123    0.0
124    0.0
125    0.0
126    0.0
127    0.0
128    0.0
129    0.0
130    0.0
131    0.0
132    0.0
133    0.0
134    0.0
135    0.0
136    0.0
137    0.0
138    0.0
139    0.0
140    0.0
141    0.0
142    0.0
143    0.0
144    0.0
145    0.0
146    0.0
147    0.0
148    0.0
149    0.0
150    0.0
151    0.0
152    0.0
153    0.0
154    0.0
155    0.0
156    0.0
157    0.0
158    0.0
159    0.0
160    0.0
161    0.0
162    0.0
163    0.0
164    0.0
165    0.0
166    0.0
167    0.0
168    0.0
169    0.0
170    0.0
171    0.0
172    0.0
173    0.0
174    0.0
175    0.0
176    0.0
177    0.0
178    0.0
179    0.0
180    0.0
181    0.0
182    0.0
183    0.0
184    0.0
185    0.0
186    0.0
187    0.0
188    0.0
189    0.0
190    0.0
191    0.0
192    0.0
193    0.0
194    0.0
195    0.0
196    0.0
197    0.0
198    0.0
199    0.0
200    0.0
201    0.0
202    0.0
203    0.0
204    0.0
205    0.0
206    0.0
207    0.0
208    0.0
209    0.0
210    0.0
211    0.0
212    0.0
213    0.0
214    0.0
215    0.0
216    0.0
217    0.0
218    0.0
219    0.0
220    0.0
221    0.0
222    0.0
223    0.0
224    0.0
225    0.0
226    0.0
227    0.0
228    0.0
229    0.0
230    0.0
231    0.0
232    0.0
233    0.0
234    0.0
235    0.0
236    0.0
237    0.0
238    0.0
239    0.0
240    0.0
241    0.0
242    0.0
243    0.0
244    0.0
245    0.0
246    0.0
247    0.0
248    0.0
249    0.0
250    0.0
251    0.0
252    0.0
253    0.0
254    0.0
255    0.0
256    0.0
257    0.0
258    0.0
259    0.0
260    0.0
261    0.0
262    0.0
263    0.0
264    0.0
265    0.0
266    0.0
267    0.0
268    0.0
269    0.0
270    0.0
271    0.0
272    0.0
273    0.0
274    0.0
275    0.0
276    0.0
277    0.0
278    0.0
279    0.0
280    0.0
281    0.0
282    0.0
283    0.0
284    0.0
285    0.0
286    0.0
287    0.0
288    0.0
289    0.0
290    0.0
291    0.0
292    0.0
293    0.0
294    0.0
295    0.0
296    0.0
297    0.0
298    0.0
299    0.0
300    0.0
301    0.0
302    0.0
303    0.0
304    0.0
305    0.0
306    0.0
307    0.0
308    0.0
309    0.0
310    0.0
311    0.0
312    0.0
313    0.0
314    0.0
315    0.0
316    0.0
317    0.0
318    0.0
319    0.0
320    0.0
321    0.0
322    0.0
323    0.0
324    0.0
325    0.0
326    0.0
327    0.0
328    0.0
329    0.0
330    0.0
331    0.0
332    0.0
333    0.0
334    0.0
335    0.0
336    0.0
337    0.0
338    0.0
339    0.0
340    0.0
341    0.0
342    0.0
343    0.0
344    0.0
345    0.0
346    0.0
347    0.0
348    0.0
349    0.0
350    0.0
351    0.0
352    0.0
353    0.0
354    0.0
355    0.0
356    0.0
357    0.0
358    0.0
359    0.0
360    0.0
361    0.0
362    0.0
363    0.0
364    0.0
365    0.0
366    0.0
367    0.0
368    0.0
369    0.0
370    0.0
371    0.0
372    0.0
373    0.0
374    0.0
375    0.0
376    0.0
377    0.0
378    0.0
379    0.0
380    0.0
381    0.0
382    0.0
383    0.0
384    0.0
385    0.0
386    0.0
387    0.0
388    0.0
389    0.0
390    0.0
391    0.0
392    0.0
393    0.0
394    0.0
395    0.0
396    0.0
397    0.0
398    0.0
399    0.0
400    0.0
401    0.0
402    0.0
403    0.0
404    0.0
405    0.0
406    0.0
407    0.0
408    0.0
409    0.0
410    0.0
411    0.0
412    0.0
413    0.0
414    0.0
415    0.0
416    0.0
417    0.0
418    0.0
419    0.0
420    0.0
421    0.0
422    0.0
423    0.0
424    0.0
425    0.0
426    0.0
427    0.0
428    0.0
429    0.0
430    0.0
431    0.0
432    0.0
433    0.0
434    0.0
435    0.0
436    0.0
437    0.0
438    0.0
439    0.0
440    0.0
441    0.0
442    0.0
443    0.0
444    0.0
445    0.0
446    0.0
447    0.0
448    0.0
449    0.0
450    0.0
451    0.0
452    0.0
453    0.0
454    0.0
455    0.0
456    0.0
457    0.0
458    0.0
459    0.0
460    0.0
461    0.0
462    0.0
463    0.0
464    0.0
465    0.0
466    0.0
467    0.0
468    0.0
469    0.0
470    0.0
471    0.0
472    0.0
473    0.0
474    0.0
475    0.0
476    0.0
477    0.0
478    0.0
479    0.0
480    0.0
481    0.0
482    0.0
483    0.0
484    0.0
485    0.0
486    0.0
487    0.0
488    0.0
489    0.0
490    0.0
491    0.0
492    0.0
493    0.0
494    0.0
495    0.0
496    0.0
497    0.0
498    0.0
...    ...
44752  0.0
44753  0.0
44754  0.0
44755  0.0
44756  0.0
44757  0.0
44758  0.0
44759  0.0
44760  0.0
44761  0.0
44762  0.0
44763  0.0
44764  0.0
44765  0.0
44766  0.0
44767  0.0
44768  0.0
44769  0.0
44770  0.0
44771  0.0
44772  0.0
44773  0.0
44774  0.0
44775  0.0
44776  0.0
44777  0.0
44778  0.0
44779  0.0
44780  0.0
44781  0.0
44782  0.0
44783  0.0
44784  0.0
44785  0.0
44786  0.0
44787  0.0
44788  0.0
44789  0.0
44790  0.0
44791  0.0
44792  0.0
44793  0.0
44794  0.0
44795  0.0
44796  0.0
44797  0.0
44798  0.0
44799  0.0
44800  0.0
44801  0.0
44802  0.0
44803  0.0
44804  0.0
44805  0.0
44806  0.0
44807  0.0
44808  0.0
44809  0.0
44810  0.0
44811  0.0
44812  0.0
44813  0.0
44814  0.0
44815  0.0
44816  0.0
44817  0.0
44818  0.0
44819  0.0
44820  0.0
44821  0.0
44822  0.0
44823  0.0
44824  0.0
44825  0.0
44826  0.0
44827  0.0
44828  0.0
44829  0.0
44830  0.0
44831  0.0
44832  0.0
44833  0.0
44834  0.0
44835  0.0
44836  0.0
44837  0.0
44838  0.0
44839  0.0
44840  0.0
44841  0.0
44842  0.0
44843  0.0
44844  0.0
44845  0.0
44846  0.0
44847  0.0
44848  0.0
44849  0.0
44850  0.0
44851  0.0
44852  0.0
44853  0.0
44854  0.0
44855  0.0
44856  0.0
44857  0.0
44858  0.0
44859  0.0
44860  0.0
44861  0.0
44862  0.0
44863  0.0
44864  0.0
44865  0.0
44866  0.0
44867  0.0
44868  0.0
44869  0.0
44870  0.0
44871  0.0
44872  0.0
44873  0.0
44874  0.0
44875  0.0
44876  0.0
44877  0.0
44878  0.0
44879  0.0
44880  0.0
44881  0.0
44882  0.0
44883  0.0
44884  0.0
44885  0.0
44886  0.0
44887  0.0
44888  0.0
44889  0.0
44890  0.0
44891  0.0
44892  0.0
44893  0.0
44894  0.0
44895  0.0
44896  0.0
44897  0.0
44898  0.0
44899  0.0
44900  0.0
44901  0.0
44902  0.0
44903  0.0
44904  0.0
44905  0.0
44906  0.0
44907  0.0
44908  0.0
44909  0.0
44910  0.0
44911  0.0
44912  0.0
44913  0.0
44914  0.0
44915  0.0
44916  0.0
44917  0.0
44918  0.0
44919  0.0
44920  0.0
44921  0.0
44922  0.0
44923  0.0
44924  0.0
44925  0.0
44926  0.0
44927  0.0
44928  0.0
44929  0.0
44930  0.0
44931  0.0
44932  0.0
44933  0.0
44934  0.0
44935  0.0
44936  0.0
44937  0.0
44938  0.0
44939  0.0
44940  0.0
44941  0.0
44942  0.0
44943  0.0
44944  0.0
44945  0.0
44946  0.0
44947  0.0
44948  0.0
44949  0.0
44950  0.0
44951  0.0
44952  0.0
44953  0.0
44954  0.0
44955  0.0
44956  0.0
44957  0.0
44958  0.0
44959  0.0
44960  0.0
44961  0.0
44962  0.0
44963  0.0
44964  0.0
44965  0.0
44966  0.0
44967  0.0
44968  0.0
44969  0.0
44970  0.0
44971  0.0
44972  0.0
44973  0.0
44974  0.0
44975  0.0
44976  0.0
44977  0.0
44978  0.0
44979  0.0
44980  0.0
44981  0.0
44982  0.0
44983  0.0
44984  0.0
44985  0.0
44986  0.0
44987  0.0
44988  0.0
44989  0.0
44990  0.0
44991  0.0
44992  0.0
44993  0.0
44994  0.0
44995  0.0
44996  0.0
44997  0.0
44998  0.0
44999  0.0
45000  0.0
45001  0.0
45002  0.0
45003  0.0
45004  0.0
45005  0.0
45006  0.0
45007  0.0
45008  0.0
45009  0.0
45010  0.0
45011  0.0
45012  0.0
45013  0.0
45014  0.0
45015  0.0
45016  0.0
45017  0.0
45018  0.0
45019  0.0
45020  0.0
45021  0.0
45022  0.0
45023  0.0
45024  0.0
45025  0.0
45026  0.0
45027  0.0
45028  0.0
45029  0.0
45030  0.0
45031  0.0
45032  0.0
45033  0.0
45034  0.0
45035  0.0
45036  0.0
45037  0.0
45038  0.0
45039  0.0
45040  0.0
45041  0.0
45042  0.0
45043  0.0
45044  0.0
45045  0.0
45046  0.0
45047  0.0
45048  0.0
45049  0.0
45050  0.0
45051  0.0
45052  0.0
45053  0.0
45054  0.0
45055  0.0
45056  0.0
45057  0.0
45058  0.0
45059  0.0
45060  0.0
45061  0.0
45062  0.0
45063  0.0
45064  0.0
45065  0.0
45066  0.0
45067  0.0
45068  0.0
45069  0.0
45070  0.0
45071  0.0
45072  0.0
45073  0.0
45074  0.0
45075  0.0
45076  0.0
45077  0.0
45078  0.0
45079  0.0
45080  0.0
45081  0.0
45082  0.0
45083  0.0
45084  0.0
45085  0.0
45086  0.0
45087  0.0
45088  0.0
45089  0.0
45090  0.0
45091  0.0
45092  0.0
45093  0.0
45094  0.0
45095  0.0
45096  0.0
45097  0.0
45098  0.0
45099  0.0
45100  0.0
45101  0.0
45102  0.0
45103  0.0
45104  0.0
45105  0.0
45106  0.0
45107  0.0
45108  0.0
45109  0.0
45110  0.0
45111  0.0
45112  0.0
45113  0.0
45114  0.0
45115  0.0
45116  0.0
45117  0.0
45118  0.0
45119  0.0
45120  0.0
45121  0.0
45122  0.0
45123  0.0
45124  0.0
45125  0.0
45126  0.0
45127  0.0
45128  0.0
45129  0.0
45130  0.0
45131  0.0
45132  0.0
45133  0.0
45134  0.0
45135  0.0
45136  0.0
45137  0.0
45138  0.0
45139  0.0
45140  0.0
45141  0.0
45142  0.0
45143  0.0
45144  0.0
45145  0.0
45146  0.0
45147  0.0
45148  0.0
45149  0.0
45150  0.0
45151  0.0
45152  0.0
45153  0.0
45154  0.0
45155  0.0
45156  0.0
45157  0.0
45158  0.0
45159  0.0
45160  0.0
45161  0.0
45162  0.0
45163  0.0
45164  0.0
45165  0.0
45166  0.0
45167  0.0
45168  0.0
45169  0.0
45170  0.0
45171  0.0
45172  0.0
45173  0.0
45174  0.0
45175  0.0
45176  0.0
45177  0.0
45178  0.0
45179  0.0
45180  0.0
45181  0.0
45182  0.0
45183  0.0
45184  0.0
45185  0.0
45186  0.0
45187  0.0
45188  0.0
45189  0.0
45190  0.0
45191  0.0
45192  0.0
45193  0.0
45194  0.0
45195  0.0
45196  0.0
45197  0.0
45198  0.0
45199  0.0
45200  0.0
45201  0.0
45202  0.0
45203  0.0
45204  0.0
45205  0.0
45206  0.0
45207  0.0
45208  0.0
45209  0.0
45210  0.0
45211  0.0
45212  0.0
45213  0.0
45214  0.0
45215  0.0
45216  0.0
45217  0.0
45218  0.0
45219  0.0
45220  0.0
45221  0.0
45222  0.0
45223  0.0
45224  0.0
45225  0.0
45226  0.0
45227  0.0
45228  0.0
45229  0.0
45230  0.0
45231  0.0
45232  0.0
45233  0.0
45234  0.0
45235  0.0
45236  0.0
45237  0.0
45238  0.0
45239  0.0
45240  0.0
45241  0.0
45242  0.0
45243  0.0
45244  0.0
45245  0.0
45246  0.0
45247  0.0
45248  0.0
45249  0.0
45250  0.0

[45251 rows x 1 columns]